version: "3"
services:
  
  php:
    image: "php:apache"
    ports:
      - "80:80"
    container_name: lemp_php2_apache
    volumes:
      - ./html:/var/www/html/
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    

  db:
    image: "mariadb:latest"
    ports:
        - "3277:3277"
        - "3306:3306"
    container_name: lemp_mariadb 
    environment:
      - MYSQL_ROOT_PASSWORD=123132123
    networks:
      - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:


    
